<?php

namespace GestionPersonelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * affiliationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class affiliationRepository extends EntityRepository
{
}
