<?php

namespace GestionPersonelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * avoir_absenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class avoir_absenceRepository extends EntityRepository
{
}
