<?php

namespace GestionPersonelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * heure_supplementaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class heure_supplementaireRepository extends EntityRepository
{
}
