<?php

namespace GestionPersonelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * type_absenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_absenceRepository extends EntityRepository
{
}
